package powerrangers.eivom.feature_movie.domain.utility

object TranslateCode {
    val GENRE = mapOf(
        28 to "Action",
        12 to "Adventure",
        16 to "Animation",
        35 to "Comedy",
        80 to "Crime",
        99 to "Documentary",
        18 to "Drama",
        10751 to "Family",
        14 to "Fantasy",
        36 to "History",
        27 to "Horror",
        10402 to "Music",
        9648 to "Mystery",
        10749 to "Romance",
//        878 to "Science Fiction",
        878 to "Sci-Fi",
        10770 to "TV-Series",
        53 to "Thriller",
        10752 to "War",
        37 to "Western"
    )

    val ISO_639_1 = mapOf(
        "ab" to "Abkhazian",
        "aa" to "Afar",
        "af" to "Afrikaans",
        "ak" to "Akan",
        "sq" to "Albanian",
        "am" to "Amharic",
        "ar" to "Arabic",
        "an" to "Aragonese",
        "hy" to "Armenian",
        "as" to "Assamese",
        "av" to "Avaric",
        "ae" to "Avestan",
        "ay" to "Aymara",
        "az" to "Azerbaijani",
        "bm" to "Bambara",
        "ba" to "Bashkir",
        "eu" to "Basque",
        "be" to "Belarusian",
        "bn" to "Bengali",
        "bi" to "Bislama",
        "bs" to "Bosnian",
        "br" to "Breton",
        "bg" to "Bulgarian",
        "my" to "Burmese",
        "ca" to "Catalan, Valencian",
        "ch" to "Chamorro",
        "ce" to "Chechen",
        "ny" to "Chichewa, Chewa, Nyanja",
        "zh" to "Chinese",
        "cu" to "Church Slavonic, Old Slavonic, Old Church Slavonic",
        "cv" to "Chuvash",
        "kw" to "Cornish",
        "co" to "Corsican",
        "cr" to "Cree",
        "hr" to "Croatian",
        "cs" to "Czech",
        "da" to "Danish",
        "dv" to "Divehi, Dhivehi, Maldivian",
        "nl" to "Dutch, Flemish",
        "dz" to "Dzongkha",
        "en" to "English",
        "eo" to "Esperanto",
        "et" to "Estonian",
        "ee" to "Ewe",
        "fo" to "Faroese",
        "fj" to "Fijian",
        "fi" to "Finnish",
        "fr" to "French",
        "fy" to "Western Frisian",
        "ff" to "Fulah",
        "gd" to "Gaelic, Scottish Gaelic",
        "gl" to "Galician",
        "lg" to "Ganda",
        "ka" to "Georgian",
        "de" to "German",
        "el" to "Greek, Modern (1453–)",
        "kl" to "Kalaallisut, Greenlandic",
        "gn" to "Guarani",
        "gu" to "Gujarati",
        "ht" to "Haitian, Haitian Creole",
        "ha" to "Hausa",
        "he" to "Hebrew",
        "hz" to "Herero",
        "hi" to "Hindi",
        "ho" to "Hiri Motu",
        "hu" to "Hungarian",
        "is" to "Icelandic",
        "io" to "Ido",
        "ig" to "Igbo",
        "id" to "Indonesian",
        "ia" to "Interlingua (International Auxiliary Language Association)",
        "ie" to "Interlingue, Occidental",
        "iu" to "Inuktitut",
        "ik" to "Inupiaq",
        "ga" to "Irish",
        "it" to "Italian",
        "ja" to "Japanese",
        "jv" to "Javanese",
        "kn" to "Kannada",
        "kr" to "Kanuri",
        "ks" to "Kashmiri",
        "kk" to "Kazakh",
        "km" to "Central Khmer",
        "ki" to "Kikuyu, Gikuyu",
        "rw" to "Kinyarwanda",
        "ky" to "Kirghiz, Kyrgyz",
        "kv" to "Komi",
        "kg" to "Kongo",
        "ko" to "Korean",
        "kj" to "Kuanyama, Kwanyama",
        "ku" to "Kurdish",
        "lo" to "Lao",
        "la" to "Latin",
        "lv" to "Latvian",
        "li" to "Limburgan, Limburger, Limburgish",
        "ln" to "Lingala",
        "lt" to "Lithuanian",
        "lu" to "Luba-Katanga",
        "lb" to "Luxembourgish, Letzeburgesch",
        "mk" to "Macedonian",
        "mg" to "Malagasy",
        "ms" to "Malay",
        "ml" to "Malayalam",
        "mt" to "Maltese",
        "gv" to "Manx",
        "mi" to "Maori",
        "mr" to "Marathi",
        "mh" to "Marshallese",
        "mn" to "Mongolian",
        "na" to "Nauru",
        "nv" to "Navajo, Navaho",
        "nd" to "North Ndebele",
        "nr" to "South Ndebele",
        "ng" to "Ndonga",
        "ne" to "Nepali",
        "no" to "Norwegian",
        "nb" to "Norwegian Bokmål",
        "nn" to "Norwegian Nynorsk",
        "ii" to "Sichuan Yi, Nuosu",
        "oc" to "Occitan",
        "oj" to "Ojibwa",
        "or" to "Oriya",
        "om" to "Oromo",
        "os" to "Ossetian, Ossetic",
        "pi" to "Pali",
        "ps" to "Pashto, Pushto",
        "fa" to "Persian",
        "pl" to "Polish",
        "pt" to "Portuguese",
        "pa" to "Punjabi, Panjabi",
        "qu" to "Quechua",
        "ro" to "Romanian, Moldavian, Moldovan",
        "rm" to "Romansh",
        "rn" to "Rundi",
        "ru" to "Russian",
        "se" to "Northern Sami",
        "sm" to "Samoan",
        "sg" to "Sango",
        "sa" to "Sanskrit",
        "sc" to "Sardinian",
        "sr" to "Serbian",
        "sn" to "Shona",
        "sd" to "Sindhi",
        "si" to "Sinhala, Sinhalese",
        "sk" to "Slovak",
        "sl" to "Slovenian",
        "so" to "Somali",
        "st" to "Southern Sotho",
        "es" to "Spanish, Castilian",
        "su" to "Sundanese",
        "sw" to "Swahili",
        "ss" to "Swati",
        "sv" to "Swedish",
        "tl" to "Tagalog",
        "ty" to "Tahitian",
        "tg" to "Tajik",
        "ta" to "Tamil",
        "tt" to "Tatar",
        "te" to "Telugu",
        "th" to "Thai",
        "bo" to "Tibetan",
        "ti" to "Tigrinya",
        "to" to "Tonga (Tonga Islands)",
        "ts" to "Tsonga",
        "tn" to "Tswana",
        "tr" to "Turkish",
        "tk" to "Turkmen",
        "tw" to "Twi",
        "ug" to "Uighur, Uyghur",
        "uk" to "Ukrainian",
        "ur" to "Urdu",
        "uz" to "Uzbek",
        "ve" to "Venda",
        "vi" to "Vietnamese",
        "vo" to "Volapük",
        "wa" to "Walloon",
        "cy" to "Welsh",
        "wo" to "Wolof",
        "xh" to "Xhosa",
        "yi" to "Yiddish",
        "yo" to "Yoruba",
        "za" to "Zhuang, Chuang",
        "zu" to "Zulu"
    )

    val ISO_3166_1 = mapOf(
        "AF" to "Afghanistan",
        "AX" to "Åland Islands",
        "AL" to "Albania",
        "DZ" to "Algeria",
        "AS" to "American Samoa",
        "AD" to "Andorra",
        "AO" to "Angola",
        "AI" to "Anguilla",
        "AQ" to "Antarctica",
        "AG" to "Antigua and Barbuda",
        "AR" to "Argentina",
        "AM" to "Armenia",
        "AW" to "Aruba",
        "AU" to "Australia",
        "AT" to "Austria",
        "AZ" to "Azerbaijan",
        "BS" to "Bahamas",
        "BH" to "Bahrain",
        "BD" to "Bangladesh",
        "BB" to "Barbados",
        "BY" to "Belarus",
        "BE" to "Belgium",
        "BZ" to "Belize",
        "BJ" to "Benin",
        "BM" to "Bermuda",
        "BT" to "Bhutan",
        "BO" to "Bolivia (Plurinational State of)",
        "BQ" to "Bonaire, Sint Eustatius and Saba",
        "BA" to "Bosnia and Herzegovina",
        "BW" to "Botswana",
        "BV" to "Bouvet Island",
        "BR" to "Brazil",
        "IO" to "British Indian Ocean Territory",
        "BN" to "Brunei Darussalam",
        "BG" to "Bulgaria",
        "BF" to "Burkina Faso",
        "BI" to "Burundi",
        "CV" to "Cabo Verde",
        "KH" to "Cambodia",
        "CM" to "Cameroon",
        "CA" to "Canada",
        "KY" to "Cayman Islands",
        "CF" to "Central African Republic",
        "TD" to "Chad",
        "CL" to "Chile",
        "CN" to "China",
        "CX" to "Christmas Island",
        "CC" to "Cocos (Keeling) Islands",
        "CO" to "Colombia",
        "KM" to "Comoros",
        "CG" to "Congo",
        "CD" to "Congo (Democratic Republic of the)",
        "CK" to "Cook Islands",
        "CR" to "Costa Rica",
        "CI" to "Côte d'Ivoire",
        "HR" to "Croatia",
        "CU" to "Cuba",
        "CW" to "Curaçao",
        "CY" to "Cyprus",
        "CZ" to "Czechia",
        "DK" to "Denmark",
        "DJ" to "Djibouti",
        "DM" to "Dominica",
        "DO" to "Dominican Republic",
        "EC" to "Ecuador",
        "EG" to "Egypt",
        "SV" to "El Salvador",
        "GQ" to "Equatorial Guinea",
        "ER" to "Eritrea",
        "EE" to "Estonia",
        "SZ" to "Eswatini",
        "ET" to "Ethiopia",
        "FK" to "Falkland Islands (Malvinas)",
        "FO" to "Faroe Islands",
        "FJ" to "Fiji",
        "FI" to "Finland",
        "FR" to "France",
        "GF" to "French Guiana",
        "PF" to "French Polynesia",
        "TF" to "French Southern Territories",
        "GA" to "Gabon",
        "GM" to "Gambia",
        "GE" to "Georgia",
        "DE" to "Germany",
        "GH" to "Ghana",
        "GI" to "Gibraltar",
        "GR" to "Greece",
        "GL" to "Greenland",
        "GD" to "Grenada",
        "GP" to "Guadeloupe",
        "GU" to "Guam",
        "GT" to "Guatemala",
        "GG" to "Guernsey",
        "GN" to "Guinea",
        "GW" to "Guinea-Bissau",
        "GY" to "Guyana",
        "HT" to "Haiti",
        "HM" to "Heard Island and McDonald Islands",
        "VA" to "Holy See",
        "HN" to "Honduras",
        "HK" to "Hong Kong",
        "HU" to "Hungary",
        "IS" to "Iceland",
        "IN" to "India",
        "ID" to "Indonesia",
        "IR" to "Iran (Islamic Republic of)",
        "IQ" to "Iraq",
        "IE" to "Ireland",
        "IM" to "Isle of Man",
        "IL" to "Israel",
        "IT" to "Italy",
        "JM" to "Jamaica",
        "JP" to "Japan",
        "JE" to "Jersey",
        "JO" to "Jordan",
        "KZ" to "Kazakhstan",
        "KE" to "Kenya",
        "KI" to "Kiribati",
        "KP" to "Korea (Democratic People's Republic of)",
        "KR" to "Korea (Republic of)",
        "KW" to "Kuwait",
        "KG" to "Kyrgyzstan",
        "LA" to "Lao People's Democratic Republic",
        "LV" to "Latvia",
        "LB" to "Lebanon",
        "LS" to "Lesotho",
        "LR" to "Liberia",
        "LY" to "Libya",
        "LI" to "Liechtenstein",
        "LT" to "Lithuania",
        "LU" to "Luxembourg",
        "MO" to "Macao",
        "MG" to "Madagascar",
        "MW" to "Malawi",
        "MY" to "Malaysia",
        "MV" to "Maldives",
        "ML" to "Mali",
        "MT" to "Malta",
        "MH" to "Marshall Islands",
        "MQ" to "Martinique",
        "MR" to "Mauritania",
        "MU" to "Mauritius",
        "YT" to "Mayotte",
        "MX" to "Mexico",
        "FM" to "Micronesia (Federated States of)",
        "MD" to "Moldova (Republic of)",
        "MC" to "Monaco",
        "MN" to "Mongolia",
        "ME" to "Montenegro",
        "MS" to "Montserrat",
        "MA" to "Morocco",
        "MZ" to "Mozambique",
        "MM" to "Myanmar",
        "NA" to "Namibia",
        "NR" to "Nauru",
        "NP" to "Nepal",
        "NL" to "Netherlands",
        "NC" to "New Caledonia",
        "NZ" to "New Zealand",
        "NI" to "Nicaragua",
        "NE" to "Niger",
        "NG" to "Nigeria",
        "NU" to "Niue",
        "NF" to "Norfolk Island",
        "MK" to "North Macedonia",
        "MP" to "Northern Mariana Islands",
        "NO" to "Norway",
        "OM" to "Oman",
        "PK" to "Pakistan",
        "PW" to "Palau",
        "PS" to "Palestine, State of",
        "PA" to "Panama",
        "PG" to "Papua New Guinea",
        "PY" to "Paraguay",
        "PE" to "Peru",
        "PH" to "Philippines",
        "PN" to "Pitcairn",
        "PL" to "Poland",
        "PT" to "Portugal",
        "PR" to "Puerto Rico",
        "QA" to "Qatar",
        "RE" to "Réunion",
        "RO" to "Romania",
        "RU" to "Russian Federation",
        "RW" to "Rwanda",
        "BL" to "Saint Barthélemy",
        "SH" to "Saint Helena, Ascension and Tristan da Cunha",
        "KN" to "Saint Kitts and Nevis",
        "LC" to "Saint Lucia",
        "MF" to "Saint Martin (French part)",
        "PM" to "Saint Pierre and Miquelon",
        "VC" to "Saint Vincent and the Grenadines",
        "WS" to "Samoa",
        "SM" to "San Marino",
        "ST" to "Sao Tome and Principe",
        "SA" to "Saudi Arabia",
        "SN" to "Senegal",
        "RS" to "Serbia",
        "SC" to "Seychelles",
        "SL" to "Sierra Leone",
        "SG" to "Singapore",
        "SX" to "Sint Maarten (Dutch part)",
        "SK" to "Slovakia",
        "SI" to "Slovenia",
        "SB" to "Solomon Islands",
        "SO" to "Somalia",
        "ZA" to "South Africa",
        "GS" to "South Georgia and the South Sandwich Islands",
        "SS" to "South Sudan",
        "ES" to "Spain",
        "LK" to "Sri Lanka",
        "SD" to "Sudan",
        "SR" to "Suriname",
        "SJ" to "Svalbard and Jan Mayen",
        "SE" to "Sweden",
        "CH" to "Switzerland",
        "SY" to "Syrian Arab Republic",
        "TW" to "Taiwan, Province of China",
        "TJ" to "Tajikistan",
        "TZ" to "Tanzania, United Republic of",
        "TH" to "Thailand",
        "TL" to "Timor-Leste",
        "TG" to "Togo",
        "TK" to "Tokelau",
        "TO" to "Tonga",
        "TT" to "Trinidad and Tobago",
        "TN" to "Tunisia",
        "TR" to "Turkey",
        "TM" to "Turkmenistan",
        "TC" to "Turks and Caicos Islands",
        "TV" to "Tuvalu",
        "UG" to "Uganda",
        "UA" to "Ukraine",
        "AE" to "United Arab Emirates",
        "GB" to "United Kingdom of Great Britain and Northern Ireland",
        "UM" to "United States Minor Outlying Islands",
        "US" to "United States of America",
        "UY" to "Uruguay",
        "UZ" to "Uzbekistan",
        "VU" to "Vanuatu",
        "VE" to "Venezuela (Bolivarian Republic of)",
        "VN" to "Viet Nam",
        "VG" to "Virgin Islands (British)",
        "VI" to "Virgin Islands (U.S.)",
        "WF" to "Wallis and Futuna",
        "EH" to "Western Sahara",
        "YE" to "Yemen",
        "ZM" to "Zambia",
        "ZW" to "Zimbabwe"
    )
}