package powerrangers.eivom.feature_movie.domain.utility

object TranslateCode {
    val GENRE = mapOf(
        28 to "Action",
        12 to "Adventure",
        16 to "Animation",
        35 to "Comedy",
        80 to "Crime",
        99 to "Documentary",
        18 to "Drama",
        10751 to "Family",
        14 to "Fantasy",
        36 to "History",
        27 to "Horror",
        10402 to "Music",
        9648 to "Mystery",
        10749 to "Romance",
        878 to "Science Fiction",
        10770 to "TV Movie",
        53 to "Thriller",
        10752 to "War",
        37 to "Western"
    )

    val ISO_639_1 = mapOf(
        "ab" to "Abkhazian",
        "aa" to "Afar",
        "af" to "Afrikaans",
        "ak" to "Akan",
        "sq" to "Albanian",
        "am" to "Amharic",
        "ar" to "Arabic",
        "an" to "Aragonese",
        "hy" to "Armenian",
        "as" to "Assamese",
        "av" to "Avaric",
        "ae" to "Avestan",
        "ay" to "Aymara",
        "az" to "Azerbaijani",
        "bm" to "Bambara",
        "ba" to "Bashkir",
        "eu" to "Basque",
        "be" to "Belarusian",
        "bn" to "Bengali",
        "bi" to "Bislama",
        "bs" to "Bosnian",
        "br" to "Breton",
        "bg" to "Bulgarian",
        "my" to "Burmese",
        "ca" to "Catalan, Valencian",
        "ch" to "Chamorro",
        "ce" to "Chechen",
        "ny" to "Chichewa, Chewa, Nyanja",
        "zh" to "Chinese",
        "cu" to "Church Slavonic, Old Slavonic, Old Church Slavonic",
        "cv" to "Chuvash",
        "kw" to "Cornish",
        "co" to "Corsican",
        "cr" to "Cree",
        "hr" to "Croatian",
        "cs" to "Czech",
        "da" to "Danish",
        "dv" to "Divehi, Dhivehi, Maldivian",
        "nl" to "Dutch, Flemish",
        "dz" to "Dzongkha",
        "en" to "English",
        "eo" to "Esperanto",
        "et" to "Estonian",
        "ee" to "Ewe",
        "fo" to "Faroese",
        "fj" to "Fijian",
        "fi" to "Finnish",
        "fr" to "French",
        "fy" to "Western Frisian",
        "ff" to "Fulah",
        "gd" to "Gaelic, Scottish Gaelic",
        "gl" to "Galician",
        "lg" to "Ganda",
        "ka" to "Georgian",
        "de" to "German",
        "el" to "Greek, Modern (1453–)",
        "kl" to "Kalaallisut, Greenlandic",
        "gn" to "Guarani",
        "gu" to "Gujarati",
        "ht" to "Haitian, Haitian Creole",
        "ha" to "Hausa",
        "he" to "Hebrew",
        "hz" to "Herero",
        "hi" to "Hindi",
        "ho" to "Hiri Motu",
        "hu" to "Hungarian",
        "is" to "Icelandic",
        "io" to "Ido",
        "ig" to "Igbo",
        "id" to "Indonesian",
        "ia" to "Interlingua (International Auxiliary Language Association)",
        "ie" to "Interlingue, Occidental",
        "iu" to "Inuktitut",
        "ik" to "Inupiaq",
        "ga" to "Irish",
        "it" to "Italian",
        "ja" to "Japanese",
        "jv" to "Javanese",
        "kn" to "Kannada",
        "kr" to "Kanuri",
        "ks" to "Kashmiri",
        "kk" to "Kazakh",
        "km" to "Central Khmer",
        "ki" to "Kikuyu, Gikuyu",
        "rw" to "Kinyarwanda",
        "ky" to "Kirghiz, Kyrgyz",
        "kv" to "Komi",
        "kg" to "Kongo",
        "ko" to "Korean",
        "kj" to "Kuanyama, Kwanyama",
        "ku" to "Kurdish",
        "lo" to "Lao",
        "la" to "Latin",
        "lv" to "Latvian",
        "li" to "Limburgan, Limburger, Limburgish",
        "ln" to "Lingala",
        "lt" to "Lithuanian",
        "lu" to "Luba-Katanga",
        "lb" to "Luxembourgish, Letzeburgesch",
        "mk" to "Macedonian",
        "mg" to "Malagasy",
        "ms" to "Malay",
        "ml" to "Malayalam",
        "mt" to "Maltese",
        "gv" to "Manx",
        "mi" to "Maori",
        "mr" to "Marathi",
        "mh" to "Marshallese",
        "mn" to "Mongolian",
        "na" to "Nauru",
        "nv" to "Navajo, Navaho",
        "nd" to "North Ndebele",
        "nr" to "South Ndebele",
        "ng" to "Ndonga",
        "ne" to "Nepali",
        "no" to "Norwegian",
        "nb" to "Norwegian Bokmål",
        "nn" to "Norwegian Nynorsk",
        "ii" to "Sichuan Yi, Nuosu",
        "oc" to "Occitan",
        "oj" to "Ojibwa",
        "or" to "Oriya",
        "om" to "Oromo",
        "os" to "Ossetian, Ossetic",
        "pi" to "Pali",
        "ps" to "Pashto, Pushto",
        "fa" to "Persian",
        "pl" to "Polish",
        "pt" to "Portuguese",
        "pa" to "Punjabi, Panjabi",
        "qu" to "Quechua",
        "ro" to "Romanian, Moldavian, Moldovan",
        "rm" to "Romansh",
        "rn" to "Rundi",
        "ru" to "Russian",
        "se" to "Northern Sami",
        "sm" to "Samoan",
        "sg" to "Sango",
        "sa" to "Sanskrit",
        "sc" to "Sardinian",
        "sr" to "Serbian",
        "sn" to "Shona",
        "sd" to "Sindhi",
        "si" to "Sinhala, Sinhalese",
        "sk" to "Slovak",
        "sl" to "Slovenian",
        "so" to "Somali",
        "st" to "Southern Sotho",
        "es" to "Spanish, Castilian",
        "su" to "Sundanese",
        "sw" to "Swahili",
        "ss" to "Swati",
        "sv" to "Swedish",
        "tl" to "Tagalog",
        "ty" to "Tahitian",
        "tg" to "Tajik",
        "ta" to "Tamil",
        "tt" to "Tatar",
        "te" to "Telugu",
        "th" to "Thai",
        "bo" to "Tibetan",
        "ti" to "Tigrinya",
        "to" to "Tonga (Tonga Islands)",
        "ts" to "Tsonga",
        "tn" to "Tswana",
        "tr" to "Turkish",
        "tk" to "Turkmen",
        "tw" to "Twi",
        "ug" to "Uighur, Uyghur",
        "uk" to "Ukrainian",
        "ur" to "Urdu",
        "uz" to "Uzbek",
        "ve" to "Venda",
        "vi" to "Vietnamese",
        "vo" to "Volapük",
        "wa" to "Walloon",
        "cy" to "Welsh",
        "wo" to "Wolof",
        "xh" to "Xhosa",
        "yi" to "Yiddish",
        "yo" to "Yoruba",
        "za" to "Zhuang, Chuang",
        "zu" to "Zulu"
    )
}